INSERT INTO known_fruits(id, name) VALUES (1, 'Apple');
INSERT INTO known_fruits(id, name) VALUES (2, 'Banana');
INSERT INTO known_fruits(id, name) VALUES (3, 'Orange');
INSERT INTO known_fruits(id, name) VALUES (4, 'Grape');
INSERT INTO known_fruits(id, name) VALUES (5, 'Strawberry');
INSERT INTO known_fruits(id, name) VALUES (6, 'Blueberry');
INSERT INTO known_fruits(id, name) VALUES (7, 'Raspberry');
INSERT INTO known_fruits(id, name) VALUES (8, 'Pineapple');
INSERT INTO known_fruits(id, name) VALUES (9, 'Watermelon');
INSERT INTO known_fruits(id, name) VALUES (10, 'Cantaloupe');
INSERT INTO known_fruits(id, name) VALUES (11, 'Peach');
INSERT INTO known_fruits(id, name) VALUES (12, 'Plum');
INSERT INTO known_fruits(id, name) VALUES (13, 'Cherry');
INSERT INTO known_fruits(id, name) VALUES (14, 'Pear');
INSERT INTO known_fruits(id, name) VALUES (15, 'Lemon');
INSERT INTO known_fruits(id, name) VALUES (16, 'Lime');
INSERT INTO known_fruits(id, name) VALUES (17, '`Mango`');
INSERT INTO known_fruits(id, name) VALUES (18, 'Coconut');
INSERT INTO known_fruits(id, name) VALUES (19, 'Apricot');
INSERT INTO known_fruits(id, name) VALUES (20, 'Nectarine');
ALTER SEQUENCE known_fruits_id_seq RESTART WITH 21;

INSERT INTO animals(id, type, age, name) VALUES (1, 'CAT', 3, 'Felix');
INSERT INTO animals(id, type, age, name) VALUES (2, 'DOG', 5, 'Stella');
INSERT INTO animals(id, type, age, name) VALUES (3, 'FISH', 1, 'Red');
